### ISSUE TITLE
handling deleted with pushQueryBuilder

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#3487] opened 2021-11-05 20:26 UTC
I'm a bit unclear about how to work with `pushQueryBuilder` after looking at both the docs and the types/tests. This issue covers updating either the docs or the tests to be consistent.

In the docs there is the following:

```
const pushQueryBuilder = doc => {
    const query = `
        mutation CreateHuman($human: HumanInput) {
            setHuman(human: $human) {
                id,
                updatedAt,
                deleted
            }
        }
    `;
    const variables = {
        human: doc
    };
    return {
        query,
        variables
    };
};
```

so it looks like `doc` should include a value for `deleted `. The tests are slightly different (and also include types):

```
    const pushQueryBuilder = (doc: RxDocumentData<HumanWithTimestampDocumentType>) => {
        if (!doc) {
            throw new Error();
        }
        const query = `
        mutation CreateHuman($human: HumanInput) {
            setHuman(human: $human) {
                id,
                updatedAt
            }
        }
        `;
        const variables = {
            human: {
                id: doc.id,
                name: doc.name,
                age: doc.age,
                updatedAt: doc.updatedAt,
                deleted: doc._deleted ? true : false
            }
        };

        return {
            query,
            variables
        };
    };
```

Here `doc._deleted` is being used and (according to typescript) `doc.deleted` isn't a thing. I expect that `doc.deleted` does exist, and the test types need to be updated (`RxDocumentData<RxDocument<HumanWithTimestampDocumentType>>`?), but I wanted to double check before moving forward.

**Comment by pubkey** [comment] 2021-11-08 02:41
Documents internally have the `_deleted` value. We do this because pouchdb also does it.
The non-lodash `deleted` is the deleted field that has been chosen for the graphql replication. You can pick any word there as long as your graphql endpoint uses that property to transfer the information if a document is deleted.

**Comment by chrisdrackett** [comment] 2021-11-09 18:29
I guess what I'm confused about is what is the `doc` provided to the `pushQueryBuilder`? It seems to me that if it is `RxDocumentData` it will have `_deleted` but not `deleted`. If it is a `RxDocument` it should have `deleted` as well as `_deleted`. This seems to be the case looking at the examples, but I wanted to verify before suggesting doc updates.

**Comment by chrisdrackett** [comment] 2021-11-09 19:23
ok, so I did some more testing and I don't see `deleted` on the doc in question when using the example given in the docs. My suggestion would be to update the docs to match what is in the tests:

```
const pushQueryBuilder = doc => {
    const query = `
        mutation CreateHuman($human: HumanInput) {
            setHuman(human: $human) {
                id,
                updatedAt,
                deleted
            }
        }
    `;
    const variables = {
        human: { …doc, deleted: doc._deleted ? true : false }
    };
    return {
        query,
        variables
    };
};
```

Another suggestion would be to update the push code to use `deletedFlag` to the query for the user, but this feels more magical and might be missed.

**Comment by chrisdrackett** [comment] 2021-11-09 19:27
also thinking more, it feels wrong to use an internal field, especially as it isn't available on the types. Open to suggestions here.

**Comment by pubkey** [comment] 2021-11-24 14:14
The deleted field is optional. If not set, the document is assumed to not be deleted.
The type `RxDocumentData` which comes as param into the pushQueryBuild, has the `_deleted` field defined.
For me this looks all correct.

**Comment by chrisdrackett** [comment] 2021-11-24 20:13
Right, but I don't think the deleted field ever makes it into the rxdb database, so it isn't possible to get that field off the object I don't think.

**Comment by pubkey** [comment] 2021-12-11 21:54
I am not sure if I fully understood the problem.
We have a unit test [here](https://github.com/pubkey/rxdb/blob/master/test/unit/replication-graphql.test.ts#L1278) that ensures that locally deleted doucments get send to the server. Doesnt this reproduce the correct behavior?

**Comment by pubkey** [comment] 2022-01-02 14:03
I am closing this. If you still have this problem, please create a test case so I can start fixing.

**Closed by pubkey** 2022-01-02 14:03 UTC
