### ISSUE TITLE
can't run react-native example

### ISSUE THREAD

**Issue by iwater** [pubkey/rxdb#159] opened 2017-05-09 18:03 UTC
after the steps from here https://github.com/pubkey/rxdb/tree/master/examples/react-native
use yarn instead of npm

![simulator screen shot 2017 5 10 1 53 05](https://cloud.githubusercontent.com/assets/108937/25865247/e65e9466-3524-11e7-911a-14a48ed590bd.png)

**Comment by pubkey** [comment] 2017-05-09 18:13
Is this a yarn-specific problem or does it also not run with npm?
I know it's unlikely that yarn is the evil, but could you test it for me?

**Comment by iwater** [comment] 2017-05-10 03:37
npm got this error
![simulator screen shot 2017 5 10 11 36 22](https://cloud.githubusercontent.com/assets/108937/25882284/fee498b4-3574-11e7-88e4-9c31435285cb.png)

**Comment by pubkey** [comment] 2017-05-17 15:21
@iwater can you retry this with the latest version 4.0.1 ?
It's possible that this works now.

**Comment by iwater** [comment] 2017-05-19 19:06
retry with the latest version 4.0.2, got that same error

**Comment by pubkey** [comment] 2017-06-06 21:34
Hi @iwater 
Can you describe your setup so that I can reproduce this?
NodeVersion, OS-type, npm-version etc..

**Comment by pubkey** [comment] 2017-06-11 16:54
The error comes with ios and i dont have or will have any apple-device to reproduce.
It also looks like the error is a problem with the react-native build, not with rxdb itself.

So I'm closing this for now with a wontfix-label. Please reopen if you know how to fix this.

**Comment by iwater** [comment] 2017-06-12 12:42
I just tried the latest example by rxdb commit
use these steps from README

```
follow installation instructions to setup your react-native environment
clone the whole RxDB-repo
go into project cd rxdb
run npm install
go to this folder cd examples/react-native
run npm install
run react-native run-ios or react-native run-android
```

test env:
NodeVersion: 8.1.0, OS-type: macOS 10.12.5, npm-version: 5.0.3

first start got this error
![simulator screen shot 2017 6 12 8 32 29](https://user-images.githubusercontent.com/108937/27034007-555d94f4-4fae-11e7-8d50-ef77c0db27ec.png)

after npm install util and restart got this error
![simulator screen shot 2017 6 12 8 39 40](https://user-images.githubusercontent.com/108937/27034247-4eff7130-4faf-11e7-816c-d88da08f22dc.png)

this unhandled promise point to util.validateCouchDBString which got a undefined argument

**Comment by iwater** [comment] 2017-06-12 14:48
I dig the source find that

create function in index.js accept four arguments in comment and direct call RxDatabase exported create function, but that function accept a object argument wrap that four arguments and in react-native example code just call with four plain arguments, so that util.validateCouchDBString failed

code in example
```
RxDB.create('heroesReactDataBase1', 'asyncstorage', 'myLongAndStupidPassword', true).then((db) => {
```

code in index.js
```
/**
 * create a database
 * @param  {string} prefix as databaseName for the storage (this can be the foldername)
 * @param  {Object} storageEngine any leveldown instance
 * @param  {String} password if the database contains encrypted fields
 * @param  {boolean} multiInstance if true, multiInstance-handling will be done
 * @return {Promise<Database>}
 */
export async function create(args) {
    return RxDatabase.create(args);
}
```

code in RxDatabase.js
```
export async function create({
    name,
    adapter,
    password,
    multiInstance = true
}) {
    util.validateCouchDBString(name);   // promise reject
```

**Comment by iwater** [comment] 2017-06-12 15:02
and in the example database name is heroesReactDataBase1,  but in util check regex is
```
const regStr = '^[a-z][a-z0-9]*$';
```
mean it should be lowercase for whole string

**Comment by iwater** [comment] 2017-06-12 15:35
and heroSchema in example is missing version as required

**Comment by iwater** [comment] 2017-06-12 16:26
#201 I made a pull request for up
BTW, because react-native have it'e es6 compile process, maybe It should be better not publish .babelrc to npm registry (because that not compatible with react-native compile env, maybe not compatible other too), and referer rxdb with
```
import * as RxDB from 'rxdb/src/';
```
instead of 
```
import * as RxDB from 'rxdb';
```
to let react-native compile rxdb source for it's env

**Comment by pubkey** [comment] 2017-06-12 16:51
Thank you for the PR!

I [added](https://github.com/pubkey/rxdb/commit/8b33bc8917071a1583b4c178b3b3368b0edd588b) babelrc to gitignore since redux and other libs also do not publish them because of webpack-build-fails.

What is the benefit of using `rxdb/src/`? I thought without babelrc, the react-native-build would just not compile the module by itself and use the path given in the package.json. Or am I wrong?

**Comment by pubkey** [comment] 2017-06-13 20:30
closing this since the original issue seems to be solved.

**Closed by pubkey** 2017-06-13 20:30 UTC
Labels: bug, example
