### ISSUE TITLE
more than 5 collections sync problem.

### ISSUE THREAD

**Issue by shalaby** [pubkey/rxdb#301] opened 2017-09-22 17:53 UTC
## Case
Bug
## Issue
I am building Angular 4 app using rxdb idk adapter on the client and Couchdb on the server.
The problem begins when collections become more than 5, rxdb makes infinite http requests to couchdb server, the connections become pending for 10 seconds then canceled.
and of course the sync is not working properly anymore.
## Info
- Environment: browser
- Adapter: IndexedDB

## Code
Because I can't install couchdb on any playground, so I made a github repo so u can clone and inspect.
https://github.com/shalaby/test
![testo 2017-09-22 20-52-43](https://user-images.githubusercontent.com/149119/30757645-187d5522-9fd8-11e7-9e8e-967d2b9f13d7.png)

**Comment by pubkey** [comment] 2017-09-22 22:04
- Is this chrome?
Please try the same with the memory-adapter and tell if the problem persists

**Comment by shalaby** [comment] 2017-09-23 02:43
I tested on Chrome and Safari, same problem.
and I tries the memory-adapter same problem.

**Comment by shalaby** [comment] 2017-09-24 18:06
@pubkey Can u plz investigate this, the repo I posted has no code just the service and app-component, I didn't post the whole app. Thanks in advance.

**Comment by pubkey** [comment] 2017-09-25 16:16
@shalaby 
- The test repo is broken and needed some fixes (polyfills missing, collection `suit` is used but not defined) etc..

I tried to reproduce this with the pouchdb-server by adding the following line to the scripts of package.json
`    "server": "pouchdb-server --host 0.0.0.0 -p 5984 -m -d /tmp/pouchdb-server/ -n true" `

Everything worked fine.
I think you have a problem in the configuration in your couchdb-server.

**Comment by shalaby** [comment] 2017-09-25 18:48
@pubkey Thanks for investigating, sorry for the broken repo, it's because I removed so much so that u can investigate easily, I updated the repo with  another existing collection.
but which polyfill is missing?
babel-polyfill is installed.
and when I remove one collection from collections array in database service the error disappears.
I searched and some one mentioned it has something to do with maximum parallel connections to the server and suggested using pouch-socket. if this is the case:
How can I use it with RXDB in this application?
Really sorry to bother u but this is very important.
Thanks in advance.

**Comment by pubkey** [comment] 2017-09-25 20:18
I do not think pouch-socket is what you need here because it is basically a remote database with socket instead of http-adapter.
If you want to sync multiple collections with a single socket, you have to create a custom sync-functionality that uses [pouchdb-replication-stream](https://github.com/pouchdb-community/pouchdb-replication-stream).
Maybe we should create a rxdb-plugin for that.

**Comment by shalaby** [comment] 2017-09-26 02:42
@pubkey Thanks a lot for caring, please see this discussion on the same problem in pouchdb:
https://github.com/pouchdb/pouchdb/issues/5012
I am in the middle of serious project and I am stuck cuz of this.
I think solving this is essential because any serious app will have more than 5 collections.

**Comment by pubkey** [comment] 2017-09-26 06:53
Here is one workaround you should try:

1. On each of your collections, add a `collection`-field for the documents which always contains the collection-name
2. Create a local pouchdb-instance
3. Replicate each collection with the single pouchdb-instance by using a query-filter on the `collection`-field [see](https://pubkey.github.io/rxdb/replication.html)
4. Replicate the pouchdb-instance with the couchdb over http

**Comment by pubkey** [comment] 2017-09-27 22:01
I'm closing this.
This is a known problem with pouchdb. Most browsers only allow up to 6 connections to the same origin.
The proposed workarround should work.

**Closed by pubkey** 2017-09-27 22:01 UTC
Labels: bug

**Comment by liederivative** [comment] 2018-05-17 13:52
@pubkey Your workaround does fails when docs are deleted. For example, if a doc is deleted from a collection, because that document is not included in the query result, then is not sync with the server, therefore the server will retained the doc, but locally it wont exists . Does it make sanse ?

**Comment by tizzle** [comment] 2018-07-30 18:42
@pubkey, i'm experiencing a problem similar to @liederivative with your workaround. Any suggestions how to deal with deleting docs? Or any ideas how to start implementing the aforementioned plugin using pouchdb-replication-stream?

**Comment by pubkey** [comment] 2018-07-31 07:48
@tizzle 
I played with replication-stream a lot, but it has some strange behavior.
I think this overall is a pouchdb-problem which should be solved for pouchdb and the solution can then be adapted to rxdb.
