### ISSUE TITLE
RxCollection not getting synced with Angular 7 within Electron

### ISSUE THREAD

**Issue by mtenrero** [pubkey/rxdb#882] opened 2019-01-12 01:48 UTC
Hello, I'm trying to sync two instances, one from angular with an external PouchDB instance but I can't get it working. 

These are my deps versions:
```json
    "pouchdb": "^7.0.0",
    "pouchdb-adapter-http": "^7.0.0",
    "pouchdb-adapter-idb": "^7.0.0",
    "pouchdb-server": "^4.1.0",
    "rxdb": "^8.0.4",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
```

## RxDB Angular Service

```typescript
import { Injectable } from '@angular/core';
import RxDB, { RxReplicationState } from 'rxdb';

import RxDBValidateModule from 'rxdb/plugins/validate';
RxDB.plugin(RxDBValidateModule);

import RxDBLeaderElectionModule from 'rxdb/plugins/leader-election';
RxDB.plugin(RxDBLeaderElectionModule);

import RxDBReplicationModule from 'rxdb/plugins/replication';
RxDB.plugin(RxDBReplicationModule);

import * as PouchdbAdapterHttp from 'pouchdb-adapter-http';
RxDB.plugin(PouchdbAdapterHttp);

import { RxVetioDatastore, RxVetioCollections } from './datastore';

const adapters = {
  websql: require('pouchdb-adapter-websql'),
  idb: require('pouchdb-adapter-idb')
};

const useAdapter = 'idb';
RxDB.plugin(adapters[useAdapter]);

const syncURL = 'http://127.0.0.1:3000/';

// schemas
import employeeSchema from './schema/employee.schema';

const collections = [
  {
    name: 'employees',
    schema: employeeSchema,
    sync: true
  }
];

@Injectable({
  providedIn: 'root'
})
export class RxdbService {

  DB_INSTANCE: RxVetioDatastore;
  replicationState: RxReplicationState;

  constructor() {}

  get db(): RxVetioDatastore {
    return this.DB_INSTANCE;
  }

  async initDB(): Promise<RxVetioDatastore> {
    const db = await RxDB.create<RxVetioCollections>({
      name: 'vetioapp',
      adapter: useAdapter,
      queryChangeDetection: true
    });

    db.waitForLeadership()
      .then(() => {
        console.log('Leader!');
    });

    // create collections
    await Promise.all(collections.map(collection => db.collection(collection)));

    collections.filter(col => col.sync).map(col => col.name).map(colName => db[colName].sync({
      remote: syncURL + colName + '/'
    }));

    this.DB_INSTANCE = db;
    return db;
  }
}
```

This service is initialized via ng APP_INITIALIZER.

Schema is correctly created and can be accessed via indexedDB debugger. Data is getting saved on it also.

Having a PouchDB in-memory server running in 3000 port locally, with a database created with the name 'employees' The data can't be synced to the remote server.

Am I doing something wrong?

**Comment by pubkey** [comment] 2019-01-12 01:58
Code loiks good. Can you check the network connection in the devtools?

**Comment by mtenrero** [comment] 2019-01-12 02:11
Nop. The request doesn’t appear in the network tab

**Comment by mtenrero** [comment] 2019-01-12 16:39
I've been analyzing the problem and It's only present running the Angular webapp embbeded into an Electron instance.

Serving the Angular app standalone using `ng serve`works as expected, and the network flow can view monitored using the DevTools:
<img width="1076" alt="devtools_network_ngserve" src="https://user-images.githubusercontent.com/6759022/51075766-6a895e80-1690-11e9-8123-1b195a06c21b.png">

But, when launching the app within Electron, using `webpack-dev-server`, and loading within electron the exposed server localhost:4200 The network monitor doesn't show the external PouchDB sync petitions:
<img width="1076" alt="electron_ng_rx_no_sync_requests" src="https://user-images.githubusercontent.com/6759022/51075795-c522ba80-1690-11e9-9905-c6aff174bc1c.png">

Setting a breakpoint on the line where the sync is declared works, so the code is succesfully loaded and executed:

<img width="1043" alt="breakpoint" src="https://user-images.githubusercontent.com/6759022/51075806-ef747800-1690-11e9-98b2-74427c755f8a.png">

**Comment by pubkey** [comment] 2019-01-12 22:35
Please set `multiInstance: false` and check if it works then

**Comment by mtenrero** [comment] 2019-01-12 22:54
Even with multiInstance set to false, the requests are not done. :(

**Comment by pubkey** [comment] 2019-01-14 22:06
@mtenrero I'm sorry but I do not think I can help based on the given information. Could you create an example repo with a reproduction?

**Comment by pubkey** [comment] 2019-02-01 21:33
Can you set `waitForLeadership: false` like desribed [here](https://rxdb.info/replication.html)

**Comment by pubkey** [comment] 2019-02-07 19:24
I'm closing this since there is no way for me to reproduce this with the given information.

**Closed by pubkey** 2019-02-07 19:24 UTC
