### ISSUE TITLE
Support getters on methods

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#150] opened 2017-04-27 17:47 UTC
## Case
Bug

## Issue
Getters not working for methods

## Info
Chrome

## Code
```js
Rx.collection({ methods: {  get url() { return this.getUrl() } } })
```

Error:

![image](https://cloud.githubusercontent.com/assets/12100/25496731/e79d41e4-2b36-11e7-9828-3ef0b5a458af.png)

**Comment by pubkey** [comment] 2017-05-03 06:03
Getters will not work, only functions are supported.
The problem is, when you call  sth like this:
```js
Rx.collection({ methods: {  get foobar() { return 'xxx'; } } })
```

Then the getter is assigned to the `methods` object. 
When RxDB read all parameters from `methods` it will also call the getter there instead of looking up the function.

**Closed** 2017-05-03 06:03 UTC

**Comment by natew** [comment] 2017-05-10 16:24
Forgive my naivety, could you do:

```
Object.getPropertyDescriptors(methods).forEach(descriptor => {
  if (typeof descriptor.get == 'function') { ... }
  // or just Object.defineProperty(RxDatabase, propName, descriptor)
})
```
