### ISSUE TITLE
Maximum call stack size exceeded during encryptString

### ISSUE THREAD

**Issue by ahoyahoy** [pubkey/rxdb#5624] opened 2024-02-10 20:11 UTC
minimal example https://github.com/ahoyahoy/rxdb-shared-worker-error/blob/crypto/src/main.ts#L41C7-L41C19
`crypto` branch

There is a "long" string `okText`.
I found one document that caused me a problem during data replication.
I gradually deleted all the props from it until there were only a few left (similar) and they together caused a problem, if I deleted one of them, no problem.
But I found that even if I take just one of them and repeat it a few times, I get the same problem. see `strangeText`

With this string I'm getting this error

helpers.js:1  Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at ab2b64 (helpers.js:1:1187)
    at encryptString (helpers.js:1:1376)

I also tried to make much longer random string and no problem.

"rxdb": "15.7.0",
"rxdb-premium": "15.7.0",

**Comment by ahoyahoy** [comment] 2024-02-11 00:12
this only happens when using wrappedKeyEncryptionWebCryptoStorage in the worker instead of the main thread

**Comment by pubkey** [comment] 2024-02-11 15:15
Could reproduce but atm I have no idea what is going on here.
`ab2b64` is basically just calling `js-base64`

```ts
export function ab2b64(arrayBuffer: ArrayBuffer): string {
    return b64EncodeUnicode(String.fromCharCode.apply(null, new Uint8Array(arrayBuffer) as any));
}

import { encode, decode } from 'js-base64';

/**
 * atob() and btoa() do not work well with non ascii chars,
 * so we have to use these helper methods instead.
 * @link https://stackoverflow.com/a/30106551/3443137
 */
// Encoding UTF8 -> base64
export function b64EncodeUnicode(str: string) {
    return encode(str);
}

```

**Comment by pubkey** [comment] 2024-02-11 23:46
I think this error only occurs inside of the worker, because web workers have a small max stack size.

Using `const strangeText = okText.repeat(8);` produces the same error even when using indexeddb and encryption in the main thread only without a worker.

**Comment by ahoyahoy** [comment] 2024-02-12 02:21
hm it's weird
I tried this encode in node, browser and Vite and no problem

https://stackblitz.com/edit/vitejs-vite-brcepd?file=src%2Fmain.ts

**Comment by pubkey** [comment] 2024-02-12 19:37
This is so strange. Running your example also works for me. I also added base64-js via cdn to a plain html file and run the code which worked. Only in my karma-browserify test setup it fails (newest chrome).

**Comment by ahoyahoy** [comment] 2024-02-13 00:04
Probably the error is not in my specific string and its repetition, but in the length of the document.
With this randomly generated text, it will reliably return an error above 125 kB of text.

function generateRandomString(length) {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    const charactersLength = characters.length;
    for (let i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

const randomText = generateRandomString(1000 * 125); // ok

in main thread ×126 will cause an error

in shared worker it's ×63 max

**Comment by ahoyahoy** [comment] 2024-02-13 00:09
maybe you have to split `arrayBuffer` into smaller chunks?

**Comment by ahoyahoy** [comment] 2024-02-13 00:49
https://stackblitz.com/edit/vitejs-vite-kgrb6y?file=src%2Fmain.ts

**Comment by pubkey** [comment] 2024-02-14 14:19
@ahoyahoy 

> With this randomly generated text, it will reliably return an error above 125 kB of text.

I could not reliably reproduce that. Can you make a stackbliz with that?

**Comment by ahoyahoy** [comment] 2024-02-14 14:47
yes, because the problem is with Uint8Array not base64-js

I updated this example https://stackblitz.com/edit/vitejs-vite-kgrb6y?file=src%2Fmain.ts

see the line 56
const strFromAb = ab2b64WithoutEncode(ab);

if you make randomText longer (more than 125), it will fail

**Comment by ahoyahoy** [comment] 2024-02-14 15:40
its your function without b64EncodeUnicode (updated by me)
export function ab2b64(arrayBuffer: ArrayBuffer): string {
    return b64EncodeUnicode(String.fromCharCode.apply(null, new Uint8Array(arrayBuffer) as any));
}
just for test in your code
https://github.com/pubkey/rxdb/issues/5624#issuecomment-1937782275

**Comment by pubkey** [comment] 2024-02-14 22:53
@ahoyahoy Can you try the latest release? This should be fixed now, I added your proposed chunking to prevent the error.
Thank you for your time and investigations, that helped a lot.

**Comment by ahoyahoy** [comment] 2024-02-17 18:57
it works, thanks :)

**Closed** 2024-02-18 00:47 UTC
