### ISSUE TITLE
Sort by sub object is not working.

### ISSUE THREAD

**Issue by Feverqwe** [pubkey/rxdb#585] opened 2018-03-24 08:47 UTC
## Case
Need sort by sub object

## Issue
`
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at objectCollate (index.es.js:287)
    at collate (index.es.js:47)
    at filterInclusiveStart (index.es.js:455)
    at eval (index.es.js:1258)
    at <anonymous>
`

## Info
  - Environment: electron
  - Adapter: IndexedDB

## Code

```js
const scheme = {
  name: 'items',
  schema: {
    version: 0,
    type: 'object',
    properties: {
      id: {
        type: 'string',
        primary: true
      },
      info: {
        type: 'object',
        properties: {
          title: {
            type: 'string',
            index: true
          },
        },
      },
    }
  }
};

const db = await RxDB.create({
  name: 'testdb',
  adapter: 'idb',
  multiInstance: false
});

const col = await db.collection(scheme);

await col.insert({id: '1', info: {title: 'test'}});

return col.find().sort('info.title').exec();
```

**Comment by pubkey** [comment] 2018-03-25 00:52
Hi @Feverqwe 
I could reproduce this. It looks like this is a problem with pouchdb-find and should be solved there.

**Comment by Feverqwe** [comment] 2018-03-25 09:50
I add disableKeyCompression and run this
```js
db.collections.items.pouch.find({selector: {}, sort: ['info.title']})
```
And its work.

**Comment by Feverqwe** [comment] 2018-03-25 12:35
I think bug here (last line)
https://github.com/pubkey/rxdb/blob/57fada595f2638f26a2bfb1485bc0c5289679920/src/rx-query.js#L410-L414
But I created issue in pouchdb maybe they will fixed it.
https://github.com/pouchdb/pouchdb/issues/7192

**Comment by pubkey** [comment] 2018-03-25 14:57
Thanks @Feverqwe for pointing this out. I added a test and a fix for this.

**Closed** 2018-03-25 14:57 UTC
Labels: BUG :beetle:, PouchDB :running_man:
