### ISSUE TITLE
Cannot sort on field(s) "timestamp" when using the default index

### ISSUE THREAD

**Issue by Upguard** [pubkey/rxdb#2763] opened 2020-12-18 22:14 UTC
## Case
Bug

## Issue
I have a leads collection and a marketing collection. Both sort by timestamp, both have timestamp set as indexes. The leads collection doesn't throw the error, the marketing collection does.

I've tried deleting the database and starting from scratch and still get the error.

```
Trace: Error: Cannot sort on field(s) "timestamp" when using the default index
│      at validateSort (C:\Users\xx\xx\xx\node_modules\pouchdb-find\lib\index.js:509:13)
│      at C:\Users\xx\xx\xx\node_modules\pouchdb-find\lib\index.js:1250:5
│      at C:\Users\xx\xx\xx\node_modules\unload\dist\lib\node.js:39:15
```

## Info
  - Environment: NodeJS, Electron
  - Adapter: LevelDB
  - Stack: NuxtJS

## Code

Here is my schema
```js
const marketingSchema = {
  title: 'Marketing',
  description: 'Contains marketing logs',
  version: 0,
  type: 'object',
  properties: {
    id: {
      type: 'string',
      primary: true
    },
    count: {
      type: 'number'
    },
    areaCodes: {
      type: 'string'
    },
    timestamp: {
      type: 'number'
    },
    required: ['id', 'timestamp', 'count', 'areaCodes'],
    indexes: ['timestamp']
  }
}
```
Here is the code that makes the database call in Nuxt
```js
  await db
      .marketing
      .find()
      .sort({ timestamp: 'desc' })
      .limit(100)
      .$
      .subscribe(results => {
        this.emails = results.map(result => result.toJSON())
      })
```

**Comment by pubkey** [comment] 2020-12-19 01:06
If you want to sort descending, you need a descending index. `indexes: ['-timestamp']`

**Comment by Upguard** [comment] 2020-12-19 01:32
> If you want to sort descending, you need a descending index. `indexes: ['-timestamp']`

I get this error.
```
UnhandledPromiseRejectionWarning: RxError (SC21): RxError:
│  SchemaCheck: given index is not defined in schema
│  Given parameters: {
│  index:"-timestamp"}
```

**Comment by Upguard** [comment] 2020-12-22 02:32
Thanks pubkey, any other suggestions?

**Comment by pubkey** [comment] 2020-12-22 04:12
I'm am not sure but it looks like a RxDB bug

**Comment by sintaxx** [comment] 2020-12-23 01:47
Has anyone found any solutions yet ?

**Comment by pubkey** [comment] 2020-12-23 03:17
Please enable pouch debugging and check which query runs.
https://github.com/pubkey/rxdb/blob/master/orga/bug-checklist.md#pouch-debug

**Comment by Upguard** [comment] 2020-12-23 23:58
This is the query I'm running that gave that output. You can see my schema for this collection in the first post.

```
await db
    .marketing
    .find()
    .sort({ timestamp: 'desc' })
    .limit(100)
    .$
    .subscribe(results => {
      this.emails = results.map(result => result.toJSON())
      this.loading = false
    })
```

OUTPUT:
```
2020-12-23T23:56:06.032Z pouchdb:find planning query { selector: {} }
│  
│  2020-12-23T23:56:06.033Z pouchdb:find query plan {
│    queryOpts: undefined,
│    index: {
│      ddoc: null,
│      name: '_all_docs',
│      type: 'special',
│      def: { fields: [Array] }
│    },
│    inMemoryFields: []
│  }
│  
│  2020-12-23T23:56:06.093Z pouchdb:find planning query {
│    selector: { timestamp: { '$gt': -1e+28 } },
│    limit: 100,
│    sort: [ { timestamp: 'desc' } ]
│  }
│  
│  2020-12-23T23:56:06.093Z pouchdb:find query plan {
│    queryOpts: { startkey: null },
│    index: {
│      ddoc: null,
│      name: '_all_docs',
│      type: 'special',
│      def: { fields: [Array] },
│      defaultUsed: true
│    },
│    inMemoryFields: [ 'timestamp' ]
│  }
│  
│  Trace: Error: Cannot sort on field(s) "timestamp" when using the default index
│      at validateSort (C:\Users\Kyle\Desktop\SBA Scraper\node_modules\pouchdb-find\lib\index.js:509:13)
│      at C:\Users\Kyle\Desktop\SBA Scraper\node_modules\pouchdb-find\lib\index.js:1250:5
│      at C:\Users\Kyle\Desktop\SBA Scraper\node_modules\unload\dist\lib\node.js:39:15
```

**Comment by Upguard** [comment] 2020-12-23 23:59
Part of that output is from a different query I'm running in the same mount function and can be ignored.

**Comment by Upguard** [comment] 2020-12-24 05:02
When comparing the marketing output to the leads output I noticed the marketing output doesn't have a startKey and the index object is different. Here's are the two for comparison.

**Leads Output**
```
│  2020-12-24T04:51:29.884Z pouchdb:find query plan {
│    queryOpts: { startkey: -1e+28, inclusive_start: false },
│    index: {
│      ddoc: '_design/idx-rxdb-index-timestamp',
│      name: 'idx-rxdb-index-timestamp',
│      type: 'json',
│      def: { fields: [Array] }
│    },
│    inMemoryFields: []
│  }
```

**Marketing Output**
```
│  2020-12-24T04:55:21.297Z pouchdb:find query plan {
│    queryOpts: { startkey: null },
│    index: {
│      ddoc: null,
│      name: '_all_docs',
│      type: 'special',
│      def: { fields: [Array] },
│      defaultUsed: true
│    },
│    inMemoryFields: [ 'timestamp' ]
│  }
```
Both of them are using the same exact queries

**Leads Query**
```
await db
    .leads
    .find()
    .sort({ timestamp: 'desc' })
    .limit(100)
    .$
    .subscribe(results => {
      this.leads = results.map(result => result.toJSON())
      this.loading = false
    })
```
**Marketing Query**
```
await db
    .marketing
    .find()
    .sort({ timestamp: 'desc' })
    .limit(100)
    .$
    .subscribe(results => {
      this.emails = results.map(result => result.toJSON())
      this.loading = false
    })
```
And here are both schemas with the indexes set to ['timestamp']

**Leads Schema**
```
const leadsSchema = {
  title: 'Leads',
  description: 'Contains all leads',
  version: 0,
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    email: {
      type: 'string',
      primary: true
    },
    company: {
      type: 'string'
    },
    areaCode: {
      type: 'string'
    },
    address: {
      type: 'string'
    },
    status: {
      type: 'string'
    },
    timestamp: {
      type: 'number'
    }
  },
  required: ['name', 'email', 'company', 'timestamp', 'areaCode', 'address'],
  indexes: ['timestamp']
}
```

**Marketing Schema**
```
const marketingSchema = {
  title: 'Marketing',
  description: 'Contains marketing logs',
  version: 0,
  type: 'object',
  properties: {
    id: {
      type: 'string',
      primary: true
    },
    count: {
      type: 'number'
    },
    areaCodes: {
      type: 'string'
    },
    timestamp: {
      type: 'number'
    },
    required: ['id', 'timestamp', 'count', 'areaCodes'],
    indexes: ['timestamp']
  }
}
```

**Comment by DDoerner** [comment] 2021-01-18 10:46
Can confirm that it seems to be a RxDB bug. We've had the same happen in our app, where an error is thrown for a property that an index exists for. 

But the strange thing is that is does not happen always. Once it occurs, restarting the app does not help, only resetting the indexed DB. So far we've not been able to deterministically reproduce it, so it might be a race condition during index creation?

In our case, it happened for the indexedDB adapter and both in Safari and Firefox browsers.

Will post additional information once it happens the next time.

**Comment by plmercereau** [comment] 2021-01-22 18:48
I'm not sure it causes the problem, but in the above marketing schema, the required and indexes keys are part of properties where I think they should be put in the schema's root.

**Comment by pubkey** [comment] 2021-01-24 00:11
Can you make a PR with a test that proves that this is broken and also that it is not a pouchdb bug?

**Comment by pubkey** [comment] 2021-02-06 19:58
@Upguard any update?

**Comment by pubkey** [comment] 2021-02-14 01:18
I am closing this as it seems noone will work on it.
We need a test which runs the same query against rxdb and pouchdb to reproduce the problem.

**Closed by pubkey** 2021-02-14 01:18 UTC
