### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by berkayk** [pubkey/rxdb#522] opened 2018-02-11 19:19 UTC
Is there any way to improve performance when inserting multiple records, similar to bulkDocs in pouchdb. I couldn't find it in the documentation.

Thanks

**Comment by pubkey** [comment] 2018-02-11 20:08
Hi @berkayk 
I'm sorry, there is currently no `bulkDocs`-like function in RxDB.
The reason is, that mostly the normal import is fast enough.
But sometimes it is not, so I recommend to use the collection-internal pouchdb for performance critical operations. You can access it by using `myCollection.pouch`.

**Comment by berkayk** [comment] 2018-02-11 20:54
Thanks for the fast response. 
So for instance, let's say I have to insert 300 records into a collection. I am currently doing it such as

    export async function insertItem(object){
      const db = await get();
      try {
        const action = await db.collection.insert(object);
        return action;
      }
      catch (error){}
    }

Is it worth using `collection.pouch`? If that will improve performance, can you give a little more detail on using it?

Thanks again :)

**Comment by berkayk** [comment] 2018-02-12 13:35
I will try both of them. How can I use by accessing `pouch` ?

**Comment by pubkey** [comment] 2018-02-13 12:25
You can access the pouchdb with `myCollection.pouch`
I'm closing this since this cannot be solved with a commit.
Please ask basic questions at the [gitter-channel](https://gitter.im/pubkey/rxdb)

**Closed by pubkey** 2018-02-13 12:25 UTC

**Comment by pubkey** [comment] 2020-11-06 17:23
EDIT 2020: There is now a `bulkInsert()` method https://rxdb.info/rx-collection.html#bulkinsert

**Comment by afazzdev** [comment] 2021-07-09 02:42
So, i'm trying to bulkInsert around 10k data, but the electron keep freezing. from what i've experiencing, pouchdb have better bulk insert than rxdb because it's not making my electron app frozen for a long time. Any  idea what the problem is?

btw, i'm using bulkInsert inside Promise.all, and doing other db operation beside that 10k data is there any problem with that?
