### ISSUE TITLE
sort doesn't work in websql adapter.

### ISSUE THREAD

**Issue by cw196** [pubkey/rxdb#726] opened 2018-07-23 03:00 UTC
The sort function will return nothing when using websql adapter, the idb is working fine.

ex. 
    db.heroes.find().sort({name: 1})

**Comment by pubkey** [comment] 2018-07-31 07:07
Hi @cw196 
Can you produce a test-case?
You can start by [editing this file](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js).

Please use the issue-template for further problems.

**Comment by pubkey** [comment] 2018-08-20 17:27
I think this is a duplicate of by #741

**Closed by pubkey** 2018-08-20 17:27 UTC
Labels: needs test case :mag_right:
