### ISSUE TITLE
Rapid RxDocument updates with idb adapter fail to propagate

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#743] opened 2018-08-08 10:58 UTC
## Case
Potential bug: rapid doc updates with idb adapter

## Issue
Rapid calls to a RxDocument `update` method will cause the document not to receive the last update. At that point, since the `_rev` differs with the last updated one, it will fail to further update anymore until the page is reloaded.

I believe the code is self-explanatory. I should note, however, this does not happen with the memory adapter as long as there is some delay in ms between updates. In summary, it seems like it shares the same problem, but since the response time is lower, the threshold for those updates to happen while causing this issue is way lower.

## Info
  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: Babel, React
  - RxDB: 7.7.1

## Code

```js
const RxDB = require('rxdb');
RxDB.plugin(require('pouchdb-adapter-idb'));

async function test() {
  const db = await RxDB.create({
    name: 'testdb',
    adapter: 'idb',
    multiInstance: false
  });

  const schema = {
    version: 0,
    type: 'object',
    primaryPath: '_id',
    properties: {
      name: {
        type: 'string'
      }
    }
  };

  const collection = await db.collection({
    name: 'person',
    schema: schema
  });

  const doc = {
    name: 'abc'
  };

  const rxDoc = await collection.insert(doc);

  let i = 0;
  let fail = false;
  let lastSuccessRev;
  let lastPromise;
  while (!fail && i < 100) {
    // Make it wait for 10ms
    await new Promise((resolve, reject) => {
      setTimeout(() => resolve(true), 10);
    });
    lastPromise = rxDoc
      .update({ $set: { name: i.toString() } })
      .then((doc) => {
        lastSuccessRev = doc._rev;
      })
      .catch(() => (fail = true));
    i++;
  }

  // The last successful revision to go through should be
  // the current rxDoc revision
  await lastPromise;
  if (lastSuccessRev !== rxDoc._rev) {
    console.log('-'.repeat(20));
    console.log('Last successful _rev:', lastSuccessRev.split('-')[0]);
    console.log('Current RxDocument _rev:', rxDoc._rev.split('-')[0]);
    console.log('-'.repeat(20) + '\n');

    // But going even further, if we make a fresh query and
    // get the _rev, it should most definitely be the latest
    const queryRev = (await collection.findOne(rxDoc._id).exec())._rev;
    if (lastSuccessRev !== queryRev) {
      console.log('Last successful _rev:', lastSuccessRev.split('-')[0]);
      console.log('New Query RxDocument _rev:', queryRev.split('-')[0]);
      console.log('-'.repeat(20) + '\n');
    }

    // The consequence of this is we'll be unable to further update the document
    await rxDoc.update({ $set: { name: 'test name' } }).catch(() => {
      console.log('Further unable to update');
      console.log('-'.repeat(20) + '\n');
    });
  }
}
test();
```

**Comment by pubkey** [comment] 2018-08-08 13:55
I am aware of this. The root-problem is how rxdb handles updates on documents. This will be rewritten for version 8.0.0. I will leave this open and add this test to the new version to ensure it is fixed there.

**Comment by pubkey** [comment] 2018-08-20 17:12
I am closing this. The problem is how `multiInstance` is handled and how the changeEvents are propagated, this is rewritten in `8.0.0` to be faster and better tested.

**Closed by pubkey** 2018-08-20 17:12 UTC

**Comment by rafamel** [comment] 2018-08-21 00:09
Sounds great, looking forwards to v8!
