### ISSUE TITLE
Leader-Election available Sockets

### ISSUE THREAD

**Issue by auryn31** [pubkey/rxdb#1916] opened 2020-02-18 08:36 UTC
I used the `waitForLeadership` to let only one tab synch the db. And it looks like it works. But if I activate this feature and open more than 3 tabs, the next tabs wont load. 
Chrome always says, `waiting for available sockets`

Did anyone had/have the same issue? 

What did i do wrong? Did I have to manually start the sync process? If I insert in one instance, master or not, it is visible in all correctly. But it seems, that multiple instances try to open a socket/long polling. 

Thanks for help.

```
newRxDb.waitForLeadership().then(() => {
   console.log(`isLeader now`);
});
```

**Comment by pubkey** [comment] 2020-02-18 08:38
Have you set `multiInstance: true` when creating the database?

**Comment by auryn31** [comment] 2020-02-18 08:39
yes

**Comment by pubkey** [comment] 2020-02-18 08:46
Where does chrome say that about the sockets?

**Comment by auryn31** [comment] 2020-02-18 08:50
Lower left. It says `waiting for available socket...` and does nothing until some socket is free and the site loads. maybe, sometimes :-D

**Comment by auryn31** [comment] 2020-02-19 09:04
It seems like the leader will be reelected after a while

**Comment by pubkey** [comment] 2020-02-19 10:09
Can you try reproducing this problem in one of the examples?

**Comment by auryn31** [comment] 2020-02-19 10:25
I am currently trying to build an standalone example to reproduce this issue

**Comment by auryn31** [comment] 2020-02-19 14:52
ok, the example works. i have to figure out whats going on in my system

**Comment by pubkey** [comment] 2020-02-26 19:04
I'm closing this because I do not think this is a RxDB problem.
For problems with the leader-election, please also check if the example-page of broadcast-channel works for you: https://pubkey.github.io/broadcast-channel/

**Closed by pubkey** 2020-02-26 19:04 UTC
