### ISSUE TITLE
Feature request: postCreate async hook

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#751] opened 2018-08-11 14:12 UTC
## Case
As the docs currently state, postCreate hooks cannot be async. An use case for this would be async hydration of docs in a collection, which would be quite useful for relationships.

**Comment by pubkey** [comment] 2018-08-15 19:25
The problem is that the creation of a document is just a call to a constructor which is sync by definition. You can still do async things in the postCreate-hook, but the document-instance will be created without awaiting the hook.

**Comment by pubkey** [comment] 2018-08-20 19:48
I am closing this because I do not think this will be solveable in the future.

**Closed by pubkey** 2018-08-20 19:48 UTC
Labels: wontfix

**Comment by rafamel** [comment] 2018-08-21 00:35
I can see your point. I would say solution for this would be to have an `RxDocument.init()` async method and whenever we're creating a new instance calling `await new RxDocument(...).init()`. Do you see any issues with considering this approach?

**Comment by pubkey** [comment] 2018-08-21 07:26
Currently when a query runs, it has these steps:

1. Query pouchdb and get an array of doc-data
2. Create RxDocuments from doc-data
3. Return an array of RxDocuments
4. Publish RxDocuments as results of the query

Because the doc-creation is sync, we always no that there can not happen anything between step 2 and 3. This ensures that the query really has the correct result at the time it emits its documents.

If the doc-creation was async, we would have to re-check if something happened to the database after step 3 and if yes, we would have to handle that change.

This makes the async-creation not impossible but tricky and prone to errors.

**Comment by rafamel** [comment] 2018-08-22 04:38
I'd say we wouldn't necessarily have to re-check for changes. The only thing we would have to ensure is that, if the async op of a previous event takes more than the op for the latest, it doesn't return after it (so essentially, keeping a queue), so they are emitted in order. This would be more than enough of a guarantee from my perspective.

I'm not relying on async here anymore for the mobx integration we talked about, so though I still think it would make some sense to implement it down the road, I definitely get your point that it might make the code a bit too cumbersome to test for.
