### ISSUE TITLE
QueryChangeDetection runs outside of the Angular Zone

### ISSUE THREAD

**Issue by DerekTBrown** [pubkey/rxdb#542] opened 2018-03-03 04:11 UTC
## Case
Bug Request

## Issue
QueryChangeDetection produces Observables which are outside of the NgZone, so change detection will not work.

## Info
  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: Typescript/Angular2+

**Comment by pubkey** [comment] 2018-03-05 21:39
Hi @DerekTBrown 
I must admit my knowledge about ng's zones is limited.
It would be nice if you could reproduce the problem in the [ng2-example](https://github.com/pubkey/rxdb/tree/master/examples/angular2), so I can fix this.

**Comment by pubkey** [comment] 2018-03-08 01:10
Yes that would be nice. Please create a PR with an extended example so I can use this to reproduce.

**Comment by DerekTBrown** [comment] 2018-03-08 16:33
The above PR updates the example to demonstrate how zone binding should be done.

**Comment by DerekTBrown** [comment] 2018-03-08 16:34
However, if you want to demonstrate the issue, remove the `.observeOnZone` line, and you will see an assertion failure.

**Comment by pubkey** [comment] 2018-03-12 17:48
Thank you for the PR, it's now a bit more clear but I still do not fully understand it.
Do you have a proposal on how to fix this?

**Comment by DerekTBrown** [comment] 2018-03-19 01:53
The PR includes the fix.  People just need to use `observeOnZone`.

**Comment by pubkey** [comment] 2018-03-19 21:46
Ah I see. Can you explain what `rxjs-ng-extras` does an why it's needed? It does not look like anyone else is using this module. Can this be reached with rxjs?

**Comment by DerekTBrown** [comment] 2018-03-25 13:29
I don't think this is something that is going to be fixed by `rxjs`, since it is a problem with the way that `rxjs` interacts with `angular`, not a problem of `rxjs` itself.

In a nutshell- Angular uses [zone.js](https://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html) to track changes to variables. Any variable you create inside of an Angular component is automatically tracked, since it is created "inside of" the Angular zone (ie in code being run by Angular).  However, observable created by the queryChangeDetection operator (`$`) are not run inside the Angular zone, since they are created in code that was not called by Angular directly (ie `rxdb`).

To solve this issue, you need a shim to recreate the observable within the Angular Zone.  Not a ton of people are using `rxjs-ng-extras` because it is a fairly small snippet of code (~30 lines), so I think most just copy and paste.

**Comment by pubkey** [comment] 2018-03-25 14:59
But currently without the shim, the change-detection works. So do we really need this?

**Comment by pubkey** [comment] 2018-04-10 09:24
Hi @DerekTBrown 
Any update on this?
For me it looks like the change-detection works as it should and we do not need this.
Did you have problems with the change-detection at the ng2-example?

**Comment by pubkey** [comment] 2018-04-19 09:14
I'm closing this because I think everything works as expected.
Reopen if you think otherwise

**Closed by pubkey** 2018-04-19 09:14 UTC

**Comment by agibalov** [comment] 2018-11-15 05:19
@pubkey As of Angular 7 and Rxdb 8.0.3 I see this behavior when I receive updates from CouchDB. The updates are there, query change detection works as expected, but because the subscription gets triggered outside of the zone, Angular doesn't see the changes. The very same handler gets called correctly for local changes. The workaround is to wrap the handler's body with `zone.run(() => ...)`. I am not familiar with `rxjs-ng-extras` library (what @DerekTBrown suggests), but I assume it does the same thing internally.

**Comment by pubkey** [comment] 2018-11-15 07:14
Hi @agibalov 
I tried many things to let the angular-zone know when rxdb queries emit new results.
It does not work by default because the RxQuery runs outside of the zone due to it's caching behavior.
What worked best for me was to use an own async-pipe which automatically runs `detectChanges` on new emits. [See here](https://github.com/pubkey/rxdb/blob/master/examples/angular2/app/src/pipes/async-no-zone.pipe.ts)

**Comment by pubkey** [comment] 2021-02-20 22:32
Changed in [this commit](https://github.com/pubkey/rxdb/commit/6571eee1ece0207fc408029ce7b2e82f7c913f8b)
Including the rxjs-zone patch should work.
```ts
import 'zone.js/dist/zone-patch-rxjs';
```
