### ISSUE TITLE
Possible sync bug

### ISSUE THREAD

**Issue by almassapargali** [pubkey/rxdb#3103] opened 2021-04-29 17:51 UTC
Because this `return` is placed inside if with condition `retryOnFail`, but it's set to false during replication, does that mean we might call push after unsuccessful pull request?

https://github.com/pubkey/rxdb/blob/7bbc78c37bc3fa579aed50c8636734bb335a84a2/src/plugins/replication-graphql/index.ts#L192

**Comment by almassapargali** [comment] 2021-04-29 17:55
We're having issues where rxdb would pull data after unsuccessful push requests, causing some data to be skipped.

**Comment by pubkey** [comment] 2021-04-29 19:00
Can you reproduce this in the CI ?

**Comment by almassapargali** [comment] 2021-04-29 19:14
You mean writing a failing test case?

**Comment by pubkey** [comment] 2021-04-30 00:08
Yes

**Comment by kuka** [comment] 2021-05-05 13:28
@almassapargali You could keep track of the failed push requests and act accordingly. It’d be interesting to see the failing test case as this is quite important for all use cases. Can you share details of your stack? What replication do you use? We need more info.

**Comment by pubkey** [comment] 2021-05-17 20:17
Closing this since it seems noone wants to work on it.

**Closed by pubkey** 2021-05-17 20:17 UTC
