### ISSUE TITLE
PrematureCommitError when executing sample Vue code from cdn

### ISSUE THREAD

**Issue by alexisread** [pubkey/rxdb#5553] opened 2024-01-26 11:37 UTC
I cannot seem to add a collection to a Dexie instance of rxdb, it errors on the addCollections function with:

```bash
zone.js:1061 Unhandled Promise rejection: Transaction committed too early. See http://bit.ly/2kdckMn ; Zone: <root> ; Task: Promise.then ; Value: r {_e: Error
    at V (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:4497)
    at new r (https://…, name: 'PrematureCommitError', message: 'Transaction committed too early. See http://bit.ly/2kdckMn', inner: null, _promise: Ae, …} PrematureCommitError: Transaction committed too early. See http://bit.ly/2kdckMn
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:82326
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:16456
    at Re (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:10851)
    at Ne (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11347)
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11198
    at rt (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:16329)
    at Fe (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11174)
    at l.invokeTask (https://cdn.jsdelivr.net/npm/zone.js@0.11.8/+esm:20:7019)
From previous: 
    at Ae.n (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:9647)
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:82287
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:16456
    at Re (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:10851)
    at Ne (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11347)
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11198
    at rt (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:16329)
    at Fe (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11174)
From previous: 
    at Function.resolve (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:13257)
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:82276
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:16456
    at Re (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:10851)
    at Ne (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11347)
    at https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11198
    at rt (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:16329)
    at Fe (https://cdn.jsdelivr.net/npm/dexie@4.0.1-beta.6/+esm:7:11174)
```

ie. it looks as though there is an existing unresolved promise before the addCollections. I'm using a cdn for the rxdb runtimes which may complicate matters. Code is below:

import { createRxDatabase, addRxPlugin }from "https://cdn.jsdelivr.net/npm/rxdb@15.3.0/+esm"
import { getRxStorageDexie } from "https://cdn.jsdelivr.net/npm/rxdb@15.3.0/dist/esm/plugins/storage-dexie/+esm"

import { RxDBDevModePlugin } from 'https://cdn.jsdelivr.net/npm/rxdb@15.3.0/dist/esm/plugins/dev-mode/+esm';
import { RxDBLeaderElectionPlugin } from 'https://cdn.jsdelivr.net/npm/rxdb@15.3.0/dist/esm/plugins/leader-election/+esm';
import { wrappedValidateAjvStorage } from 'https://cdn.jsdelivr.net/npm/rxdb@15.3.0/dist/esm/plugins/validate-ajv/+esm';

addRxPlugin(RxDBDevModePlugin);
addRxPlugin(RxDBLeaderElectionPlugin);

export async function createDatabase() {
    let db = await createRxDatabase({
        name: 'heroes', // the name of the database
        storage: wrappedValidateAjvStorage({
            storage: getRxStorageDexie()
        })
    })
    console.log('DatabaseService: created database');
    window.db = db; // write to window for debugging

    db.waitForLeadership().then(() => {
        console.log('I am the leader now')
    })

    const mySchema = {
        "title": "hero schema",
        "version": 0,
        "description": "describes a simple hero",
        "primaryKey": "name",
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "maxLength": 100 // <- the primary key must have set maxLength
            },
            "color": {
                "type": "string"
            },
            "healthpoints": {
                "type": "number",
                "minimum": 0,
                "maximum": 100
            },
            "secret": {
                "type": "string"
            },
            "birthyear": {
                "type": "number",
                "final": true,
                "minimum": 1900,
                "maximum": 2050
            },
            "skills": {
                "type": "array",
                "maxItems": 5,
                "uniqueItems": true,
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "damage": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "required": [
            "name",
            "color"
        ],
        "encrypted": ["secret"],
        "attachments": {
            "encrypted": true
        }
    }
    if (!db.heroes) {
      console.log('DatabaseService: create collections');
      await db.addCollections({heroes: { schema: mySchema}})
      console.dir(db.heroes.name);
    }
}

This function is called from a vue component as below:
export default {
    async setup() {
      let db = await createDatabase();
      return db;
    }
}

I can't seem to access the underlying Dexie instance to resolve the promise, am I missing anything here?
Thanks

**Comment by pubkey** [comment] 2024-01-27 21:02
I am sorry, I have no clue what is happening here. Maybe you should start with a reproduction unit test

**Comment by pubkey** [comment] 2024-01-27 21:04
Also updating to newest RxDB version could fix that because it has an updated dexie version.

**Comment by pubkey** [comment] 2024-02-07 22:05
Closing this. Please update to the latest RxDB version.

**Closed by pubkey** 2024-02-07 22:05 UTC
Labels: needs test case :mag_right:
