### ISSUE TITLE
Loki RxStorage doesn't treat a missing gql `deletedFlag` as falsy

### ISSUE THREAD

**Issue by ofekd** [pubkey/rxdb#3574] opened 2021-12-16 22:40 UTC
Been trying out the new Loki RxStorage, but had a problem that is inconsistent with the pouch adapter.

One of my collections has a `deletedFlag` defined for GraphQL replication but the BE isn't sending it, as documents for that collection are rarely deleted.

While pouch works as expected and uses the missing flag as a falsy value for `_deleted`, Loki causes items to disappear from RxDB after they've been replicated, if that same flag is missing.

This was tested on both `v10.5.4` and `11.0.0-beta.8`

**Comment by pubkey** [comment] 2021-12-17 00:28
Hmm this looks strange. Can you create a test case? I will then work on a fix.
There is the long term plan to make `_deleted` required on all data when RxDB communicates with the RxStorage, but I had no time to implement that yet. This might also fix your problem.

**Comment by ofekd** [comment] 2021-12-17 10:03
Alright I looked a bit into this. Didn't have time to write a test but maybe this can help you pinpoint the issue.

I've checked IndexedDB, and for documents created using `db.coll.insert`, a `_deleted: false` is added. When that same document is updated through graphql pull with missing `deletedFlag`, the `_deleted: false` property is removed.

**Comment by pubkey** [comment] 2021-12-18 17:12
Sorry I do not have the time to search around and  to try to reproduce your problem.
If you provide a test to reproduce, I will work on a fix, that's the most I can do.

**Comment by ofekd** [comment] 2021-12-18 21:11
Hi, did not expect you to, just giving you whatever information I have.

This is solved for me by having the BE include the flag, but I still hope to find the time to write a proper test.

**Comment by pubkey** [comment] 2022-01-02 14:02
@ofekd Sorry I did not want to sound mean.
If you find the time, it would be good to have a test case for the problem.
Since you find a workaround, I am closing this issue.

Maybe related: #3487

**Closed by pubkey** 2022-01-02 14:02 UTC
